// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ZProto.proto

package zproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZIPCPacket struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*ZIPCPacket_PingRequest
	//	*ZIPCPacket_PingResponse
	//	*ZIPCPacket_TestPacket
	Message       isZIPCPacket_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZIPCPacket) Reset() {
	*x = ZIPCPacket{}
	mi := &file_ZProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZIPCPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZIPCPacket) ProtoMessage() {}

func (x *ZIPCPacket) ProtoReflect() protoreflect.Message {
	mi := &file_ZProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZIPCPacket.ProtoReflect.Descriptor instead.
func (*ZIPCPacket) Descriptor() ([]byte, []int) {
	return file_ZProto_proto_rawDescGZIP(), []int{0}
}

func (x *ZIPCPacket) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ZIPCPacket) GetMessage() isZIPCPacket_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ZIPCPacket) GetPingRequest() *PingRequest {
	if x != nil {
		if x, ok := x.Message.(*ZIPCPacket_PingRequest); ok {
			return x.PingRequest
		}
	}
	return nil
}

func (x *ZIPCPacket) GetPingResponse() *PingResponse {
	if x != nil {
		if x, ok := x.Message.(*ZIPCPacket_PingResponse); ok {
			return x.PingResponse
		}
	}
	return nil
}

func (x *ZIPCPacket) GetTestPacket() *TestPacket {
	if x != nil {
		if x, ok := x.Message.(*ZIPCPacket_TestPacket); ok {
			return x.TestPacket
		}
	}
	return nil
}

type isZIPCPacket_Message interface {
	isZIPCPacket_Message()
}

type ZIPCPacket_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,2,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type ZIPCPacket_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,3,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

type ZIPCPacket_TestPacket struct {
	TestPacket *TestPacket `protobuf:"bytes,4,opt,name=test_packet,json=testPacket,proto3,oneof"`
}

func (*ZIPCPacket_PingRequest) isZIPCPacket_Message() {}

func (*ZIPCPacket_PingResponse) isZIPCPacket_Message() {}

func (*ZIPCPacket_TestPacket) isZIPCPacket_Message() {}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ZProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ZProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ZProto_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ZProto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ZProto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ZProto_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type TestPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPacket) Reset() {
	*x = TestPacket{}
	mi := &file_ZProto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPacket) ProtoMessage() {}

func (x *TestPacket) ProtoReflect() protoreflect.Message {
	mi := &file_ZProto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPacket.ProtoReflect.Descriptor instead.
func (*TestPacket) Descriptor() ([]byte, []int) {
	return file_ZProto_proto_rawDescGZIP(), []int{3}
}

func (x *TestPacket) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TestPacket) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_ZProto_proto protoreflect.FileDescriptor

const file_ZProto_proto_rawDesc = "" +
	"\n" +
	"\fZProto.proto\x12\x06zproto\"\xe4\x01\n" +
	"\n" +
	"ZIPCPacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x128\n" +
	"\fping_request\x18\x02 \x01(\v2\x13.zproto.PingRequestH\x00R\vpingRequest\x12;\n" +
	"\rping_response\x18\x03 \x01(\v2\x14.zproto.PingResponseH\x00R\fpingResponse\x125\n" +
	"\vtest_packet\x18\x04 \x01(\v2\x12.zproto.TestPacketH\x00R\n" +
	"testPacketB\t\n" +
	"\amessage\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"T\n" +
	"\n" +
	"TestPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp2v\n" +
	"\vTestService\x121\n" +
	"\x04Ping\x12\x13.zproto.PingRequest\x1a\x14.zproto.PingResponse\x124\n" +
	"\bSendData\x12\x12.zproto.TestPacket\x1a\x14.zproto.PingResponseB\x12Z\x10api/grpc/zproto/b\x06proto3"

var (
	file_ZProto_proto_rawDescOnce sync.Once
	file_ZProto_proto_rawDescData []byte
)

func file_ZProto_proto_rawDescGZIP() []byte {
	file_ZProto_proto_rawDescOnce.Do(func() {
		file_ZProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ZProto_proto_rawDesc), len(file_ZProto_proto_rawDesc)))
	})
	return file_ZProto_proto_rawDescData
}

var file_ZProto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ZProto_proto_goTypes = []any{
	(*ZIPCPacket)(nil),   // 0: zproto.ZIPCPacket
	(*PingRequest)(nil),  // 1: zproto.PingRequest
	(*PingResponse)(nil), // 2: zproto.PingResponse
	(*TestPacket)(nil),   // 3: zproto.TestPacket
}
var file_ZProto_proto_depIdxs = []int32{
	1, // 0: zproto.ZIPCPacket.ping_request:type_name -> zproto.PingRequest
	2, // 1: zproto.ZIPCPacket.ping_response:type_name -> zproto.PingResponse
	3, // 2: zproto.ZIPCPacket.test_packet:type_name -> zproto.TestPacket
	1, // 3: zproto.TestService.Ping:input_type -> zproto.PingRequest
	3, // 4: zproto.TestService.SendData:input_type -> zproto.TestPacket
	2, // 5: zproto.TestService.Ping:output_type -> zproto.PingResponse
	2, // 6: zproto.TestService.SendData:output_type -> zproto.PingResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ZProto_proto_init() }
func file_ZProto_proto_init() {
	if File_ZProto_proto != nil {
		return
	}
	file_ZProto_proto_msgTypes[0].OneofWrappers = []any{
		(*ZIPCPacket_PingRequest)(nil),
		(*ZIPCPacket_PingResponse)(nil),
		(*ZIPCPacket_TestPacket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ZProto_proto_rawDesc), len(file_ZProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ZProto_proto_goTypes,
		DependencyIndexes: file_ZProto_proto_depIdxs,
		MessageInfos:      file_ZProto_proto_msgTypes,
	}.Build()
	File_ZProto_proto = out.File
	file_ZProto_proto_goTypes = nil
	file_ZProto_proto_depIdxs = nil
}
