// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/zcore.proto

package zcoreproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZCoreService_Register_FullMethodName   = "/zcoreproto.ZCoreService/Register"
	ZCoreService_Ping_FullMethodName       = "/zcoreproto.ZCoreService/Ping"
	ZCoreService_Request2FA_FullMethodName = "/zcoreproto.ZCoreService/Request2FA"
)

// ZCoreServiceClient is the client API for ZCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZCoreServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Request2FA(ctx context.Context, in *TwoFARequest, opts ...grpc.CallOption) (*TwoFAResponse, error)
}

type zCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZCoreServiceClient(cc grpc.ClientConnInterface) ZCoreServiceClient {
	return &zCoreServiceClient{cc}
}

func (c *zCoreServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ZCoreService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCoreServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ZCoreService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCoreServiceClient) Request2FA(ctx context.Context, in *TwoFARequest, opts ...grpc.CallOption) (*TwoFAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TwoFAResponse)
	err := c.cc.Invoke(ctx, ZCoreService_Request2FA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZCoreServiceServer is the server API for ZCoreService service.
// All implementations must embed UnimplementedZCoreServiceServer
// for forward compatibility.
type ZCoreServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Request2FA(context.Context, *TwoFARequest) (*TwoFAResponse, error)
	mustEmbedUnimplementedZCoreServiceServer()
}

// UnimplementedZCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZCoreServiceServer struct{}

func (UnimplementedZCoreServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedZCoreServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedZCoreServiceServer) Request2FA(context.Context, *TwoFARequest) (*TwoFAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Request2FA not implemented")
}
func (UnimplementedZCoreServiceServer) mustEmbedUnimplementedZCoreServiceServer() {}
func (UnimplementedZCoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeZCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZCoreServiceServer will
// result in compilation errors.
type UnsafeZCoreServiceServer interface {
	mustEmbedUnimplementedZCoreServiceServer()
}

func RegisterZCoreServiceServer(s grpc.ServiceRegistrar, srv ZCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedZCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZCoreService_ServiceDesc, srv)
}

func _ZCoreService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCoreServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZCoreService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCoreServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCoreService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCoreServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZCoreService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCoreServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCoreService_Request2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCoreServiceServer).Request2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZCoreService_Request2FA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCoreServiceServer).Request2FA(ctx, req.(*TwoFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZCoreService_ServiceDesc is the grpc.ServiceDesc for ZCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zcoreproto.ZCoreService",
	HandlerType: (*ZCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ZCoreService_Register_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _ZCoreService_Ping_Handler,
		},
		{
			MethodName: "Request2FA",
			Handler:    _ZCoreService_Request2FA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/zcore.proto",
}

const (
	ZNodeController_StartEnrollment_FullMethodName = "/zcoreproto.ZNodeController/StartEnrollment"
)

// ZNodeControllerClient is the client API for ZNodeController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZNodeControllerClient interface {
	StartEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
}

type zNodeControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewZNodeControllerClient(cc grpc.ClientConnInterface) ZNodeControllerClient {
	return &zNodeControllerClient{cc}
}

func (c *zNodeControllerClient) StartEnrollment(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, ZNodeController_StartEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZNodeControllerServer is the server API for ZNodeController service.
// All implementations must embed UnimplementedZNodeControllerServer
// for forward compatibility.
type ZNodeControllerServer interface {
	StartEnrollment(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error)
	mustEmbedUnimplementedZNodeControllerServer()
}

// UnimplementedZNodeControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZNodeControllerServer struct{}

func (UnimplementedZNodeControllerServer) StartEnrollment(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartEnrollment not implemented")
}
func (UnimplementedZNodeControllerServer) mustEmbedUnimplementedZNodeControllerServer() {}
func (UnimplementedZNodeControllerServer) testEmbeddedByValue()                         {}

// UnsafeZNodeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZNodeControllerServer will
// result in compilation errors.
type UnsafeZNodeControllerServer interface {
	mustEmbedUnimplementedZNodeControllerServer()
}

func RegisterZNodeControllerServer(s grpc.ServiceRegistrar, srv ZNodeControllerServer) {
	// If the following call panics, it indicates UnimplementedZNodeControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZNodeController_ServiceDesc, srv)
}

func _ZNodeController_StartEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZNodeControllerServer).StartEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZNodeController_StartEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZNodeControllerServer).StartEnrollment(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZNodeController_ServiceDesc is the grpc.ServiceDesc for ZNodeController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZNodeController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zcoreproto.ZNodeController",
	HandlerType: (*ZNodeControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartEnrollment",
			Handler:    _ZNodeController_StartEnrollment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/zcore.proto",
}
