// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/zpipcproto.proto

package zpipcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type MatchTemplateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LiveTemplateData []byte                 `protobuf:"bytes,2,opt,name=live_template_data,json=liveTemplateData,proto3" json:"live_template_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MatchTemplateRequest) Reset() {
	*x = MatchTemplateRequest{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTemplateRequest) ProtoMessage() {}

func (x *MatchTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTemplateRequest.ProtoReflect.Descriptor instead.
func (*MatchTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{2}
}

func (x *MatchTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchTemplateRequest) GetLiveTemplateData() []byte {
	if x != nil {
		return x.LiveTemplateData
	}
	return nil
}

type MatchTemplateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsMatch         bool                   `protobuf:"varint,1,opt,name=is_match,json=isMatch,proto3" json:"is_match,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchTemplateResponse) Reset() {
	*x = MatchTemplateResponse{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTemplateResponse) ProtoMessage() {}

func (x *MatchTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTemplateResponse.ProtoReflect.Descriptor instead.
func (*MatchTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{3}
}

func (x *MatchTemplateResponse) GetIsMatch() bool {
	if x != nil {
		return x.IsMatch
	}
	return false
}

func (x *MatchTemplateResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *MatchTemplateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FetchTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTemplateRequest) Reset() {
	*x = FetchTemplateRequest{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTemplateRequest) ProtoMessage() {}

func (x *FetchTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTemplateRequest.ProtoReflect.Descriptor instead.
func (*FetchTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{4}
}

func (x *FetchTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FetchTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TemplateData  []byte                 `protobuf:"bytes,2,opt,name=template_data,json=templateData,proto3" json:"template_data,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTemplateResponse) Reset() {
	*x = FetchTemplateResponse{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTemplateResponse) ProtoMessage() {}

func (x *FetchTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTemplateResponse.ProtoReflect.Descriptor instead.
func (*FetchTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{5}
}

func (x *FetchTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchTemplateResponse) GetTemplateData() []byte {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *FetchTemplateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StoreTemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId      string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateType    string                 `protobuf:"bytes,3,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"`
	RawTemplateData []byte                 `protobuf:"bytes,4,opt,name=raw_template_data,json=rawTemplateData,proto3" json:"raw_template_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreTemplateRequest) Reset() {
	*x = StoreTemplateRequest{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTemplateRequest) ProtoMessage() {}

func (x *StoreTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTemplateRequest.ProtoReflect.Descriptor instead.
func (*StoreTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{6}
}

func (x *StoreTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *StoreTemplateRequest) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

func (x *StoreTemplateRequest) GetRawTemplateData() []byte {
	if x != nil {
		return x.RawTemplateData
	}
	return nil
}

type StoreTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTemplateResponse) Reset() {
	*x = StoreTemplateResponse{}
	mi := &file_api_proto_zpipcproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTemplateResponse) ProtoMessage() {}

func (x *StoreTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zpipcproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTemplateResponse.ProtoReflect.Descriptor instead.
func (*StoreTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zpipcproto_proto_rawDescGZIP(), []int{7}
}

func (x *StoreTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreTemplateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_zpipcproto_proto protoreflect.FileDescriptor

const file_api_proto_zpipcproto_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/zpipcproto.proto\x12\n" +
	"zpipcproto\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"]\n" +
	"\x14MatchTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12live_template_data\x18\x02 \x01(\fR\x10liveTemplateData\"\x82\x01\n" +
	"\x15MatchTemplateResponse\x12\x19\n" +
	"\bis_match\x18\x01 \x01(\bR\aisMatch\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"/\n" +
	"\x14FetchTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"{\n" +
	"\x15FetchTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rtemplate_data\x18\x02 \x01(\fR\ftemplateData\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa1\x01\n" +
	"\x14StoreTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12#\n" +
	"\rtemplate_type\x18\x03 \x01(\tR\ftemplateType\x12*\n" +
	"\x11raw_template_data\x18\x04 \x01(\fR\x0frawTemplateData\"V\n" +
	"\x15StoreTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2H\n" +
	"\vPingService\x129\n" +
	"\x04Ping\x12\x17.zpipcproto.PingRequest\x1a\x18.zpipcproto.PingResponse2\xa4\x02\n" +
	"\x0eCrypticService\x12]\n" +
	"\x16FetchDecryptedTemplate\x12 .zpipcproto.FetchTemplateRequest\x1a!.zpipcproto.FetchTemplateResponse\x12]\n" +
	"\x16StoreEncryptedTemplate\x12 .zpipcproto.StoreTemplateRequest\x1a!.zpipcproto.StoreTemplateResponse\x12T\n" +
	"\rMatchTemplate\x12 .zpipcproto.MatchTemplateRequest\x1a!.zpipcproto.MatchTemplateResponseB\x1cZ\x1a./internal/pkg/zpipcproto/b\x06proto3"

var (
	file_api_proto_zpipcproto_proto_rawDescOnce sync.Once
	file_api_proto_zpipcproto_proto_rawDescData []byte
)

func file_api_proto_zpipcproto_proto_rawDescGZIP() []byte {
	file_api_proto_zpipcproto_proto_rawDescOnce.Do(func() {
		file_api_proto_zpipcproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_zpipcproto_proto_rawDesc), len(file_api_proto_zpipcproto_proto_rawDesc)))
	})
	return file_api_proto_zpipcproto_proto_rawDescData
}

var file_api_proto_zpipcproto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_zpipcproto_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: zpipcproto.PingRequest
	(*PingResponse)(nil),          // 1: zpipcproto.PingResponse
	(*MatchTemplateRequest)(nil),  // 2: zpipcproto.MatchTemplateRequest
	(*MatchTemplateResponse)(nil), // 3: zpipcproto.MatchTemplateResponse
	(*FetchTemplateRequest)(nil),  // 4: zpipcproto.FetchTemplateRequest
	(*FetchTemplateResponse)(nil), // 5: zpipcproto.FetchTemplateResponse
	(*StoreTemplateRequest)(nil),  // 6: zpipcproto.StoreTemplateRequest
	(*StoreTemplateResponse)(nil), // 7: zpipcproto.StoreTemplateResponse
}
var file_api_proto_zpipcproto_proto_depIdxs = []int32{
	0, // 0: zpipcproto.PingService.Ping:input_type -> zpipcproto.PingRequest
	4, // 1: zpipcproto.CrypticService.FetchDecryptedTemplate:input_type -> zpipcproto.FetchTemplateRequest
	6, // 2: zpipcproto.CrypticService.StoreEncryptedTemplate:input_type -> zpipcproto.StoreTemplateRequest
	2, // 3: zpipcproto.CrypticService.MatchTemplate:input_type -> zpipcproto.MatchTemplateRequest
	1, // 4: zpipcproto.PingService.Ping:output_type -> zpipcproto.PingResponse
	5, // 5: zpipcproto.CrypticService.FetchDecryptedTemplate:output_type -> zpipcproto.FetchTemplateResponse
	7, // 6: zpipcproto.CrypticService.StoreEncryptedTemplate:output_type -> zpipcproto.StoreTemplateResponse
	3, // 7: zpipcproto.CrypticService.MatchTemplate:output_type -> zpipcproto.MatchTemplateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_zpipcproto_proto_init() }
func file_api_proto_zpipcproto_proto_init() {
	if File_api_proto_zpipcproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_zpipcproto_proto_rawDesc), len(file_api_proto_zpipcproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_zpipcproto_proto_goTypes,
		DependencyIndexes: file_api_proto_zpipcproto_proto_depIdxs,
		MessageInfos:      file_api_proto_zpipcproto_proto_msgTypes,
	}.Build()
	File_api_proto_zpipcproto_proto = out.File
	file_api_proto_zpipcproto_proto_goTypes = nil
	file_api_proto_zpipcproto_proto_depIdxs = nil
}
