// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/zfusion.proto

package zfusionproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FusionCaptureService_FusionCapture_FullMethodName = "/zfusion.FusionCaptureService/FusionCapture"
)

// FusionCaptureServiceClient is the client API for FusionCaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FusionCaptureServiceClient interface {
	FusionCapture(ctx context.Context, in *ZFusionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ZFusionResponse], error)
}

type fusionCaptureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFusionCaptureServiceClient(cc grpc.ClientConnInterface) FusionCaptureServiceClient {
	return &fusionCaptureServiceClient{cc}
}

func (c *fusionCaptureServiceClient) FusionCapture(ctx context.Context, in *ZFusionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ZFusionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FusionCaptureService_ServiceDesc.Streams[0], FusionCaptureService_FusionCapture_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ZFusionRequest, ZFusionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FusionCaptureService_FusionCaptureClient = grpc.ServerStreamingClient[ZFusionResponse]

// FusionCaptureServiceServer is the server API for FusionCaptureService service.
// All implementations must embed UnimplementedFusionCaptureServiceServer
// for forward compatibility.
type FusionCaptureServiceServer interface {
	FusionCapture(*ZFusionRequest, grpc.ServerStreamingServer[ZFusionResponse]) error
	mustEmbedUnimplementedFusionCaptureServiceServer()
}

// UnimplementedFusionCaptureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFusionCaptureServiceServer struct{}

func (UnimplementedFusionCaptureServiceServer) FusionCapture(*ZFusionRequest, grpc.ServerStreamingServer[ZFusionResponse]) error {
	return status.Error(codes.Unimplemented, "method FusionCapture not implemented")
}
func (UnimplementedFusionCaptureServiceServer) mustEmbedUnimplementedFusionCaptureServiceServer() {}
func (UnimplementedFusionCaptureServiceServer) testEmbeddedByValue()                              {}

// UnsafeFusionCaptureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FusionCaptureServiceServer will
// result in compilation errors.
type UnsafeFusionCaptureServiceServer interface {
	mustEmbedUnimplementedFusionCaptureServiceServer()
}

func RegisterFusionCaptureServiceServer(s grpc.ServiceRegistrar, srv FusionCaptureServiceServer) {
	// If the following call panics, it indicates UnimplementedFusionCaptureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FusionCaptureService_ServiceDesc, srv)
}

func _FusionCaptureService_FusionCapture_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ZFusionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FusionCaptureServiceServer).FusionCapture(m, &grpc.GenericServerStream[ZFusionRequest, ZFusionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FusionCaptureService_FusionCaptureServer = grpc.ServerStreamingServer[ZFusionResponse]

// FusionCaptureService_ServiceDesc is the grpc.ServiceDesc for FusionCaptureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FusionCaptureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zfusion.FusionCaptureService",
	HandlerType: (*FusionCaptureServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FusionCapture",
			Handler:       _FusionCaptureService_FusionCapture_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/zfusion.proto",
}
