// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/zfusion.proto

package zfusionproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZFusionResponse_PHASE int32

const (
	ZFusionResponse_PHASE_ROI    ZFusionResponse_PHASE = 0
	ZFusionResponse_PHASE_FUSION ZFusionResponse_PHASE = 1
)

// Enum value maps for ZFusionResponse_PHASE.
var (
	ZFusionResponse_PHASE_name = map[int32]string{
		0: "PHASE_ROI",
		1: "PHASE_FUSION",
	}
	ZFusionResponse_PHASE_value = map[string]int32{
		"PHASE_ROI":    0,
		"PHASE_FUSION": 1,
	}
)

func (x ZFusionResponse_PHASE) Enum() *ZFusionResponse_PHASE {
	p := new(ZFusionResponse_PHASE)
	*p = x
	return p
}

func (x ZFusionResponse_PHASE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZFusionResponse_PHASE) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_zfusion_proto_enumTypes[0].Descriptor()
}

func (ZFusionResponse_PHASE) Type() protoreflect.EnumType {
	return &file_api_proto_zfusion_proto_enumTypes[0]
}

func (x ZFusionResponse_PHASE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZFusionResponse_PHASE.Descriptor instead.
func (ZFusionResponse_PHASE) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_zfusion_proto_rawDescGZIP(), []int{1, 0}
}

type ZFusionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZFusionRequest) Reset() {
	*x = ZFusionRequest{}
	mi := &file_api_proto_zfusion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZFusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZFusionRequest) ProtoMessage() {}

func (x *ZFusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zfusion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZFusionRequest.ProtoReflect.Descriptor instead.
func (*ZFusionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zfusion_proto_rawDescGZIP(), []int{0}
}

func (x *ZFusionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ZFusionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletionPhase ZFusionResponse_PHASE  `protobuf:"varint,1,opt,name=completion_phase,json=completionPhase,proto3,enum=zfusion.ZFusionResponse_PHASE" json:"completion_phase,omitempty"`
	FusionBitstream []byte                 `protobuf:"bytes,2,opt,name=fusion_bitstream,json=fusionBitstream,proto3" json:"fusion_bitstream,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ZFusionResponse) Reset() {
	*x = ZFusionResponse{}
	mi := &file_api_proto_zfusion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZFusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZFusionResponse) ProtoMessage() {}

func (x *ZFusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zfusion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZFusionResponse.ProtoReflect.Descriptor instead.
func (*ZFusionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zfusion_proto_rawDescGZIP(), []int{1}
}

func (x *ZFusionResponse) GetCompletionPhase() ZFusionResponse_PHASE {
	if x != nil {
		return x.CompletionPhase
	}
	return ZFusionResponse_PHASE_ROI
}

func (x *ZFusionResponse) GetFusionBitstream() []byte {
	if x != nil {
		return x.FusionBitstream
	}
	return nil
}

func (x *ZFusionResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_api_proto_zfusion_proto protoreflect.FileDescriptor

const file_api_proto_zfusion_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/zfusion.proto\x12\azfusion\"/\n" +
	"\x0eZFusionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd8\x01\n" +
	"\x0fZFusionResponse\x12I\n" +
	"\x10completion_phase\x18\x01 \x01(\x0e2\x1e.zfusion.ZFusionResponse.PHASER\x0fcompletionPhase\x12)\n" +
	"\x10fusion_bitstream\x18\x02 \x01(\fR\x0ffusionBitstream\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\"(\n" +
	"\x05PHASE\x12\r\n" +
	"\tPHASE_ROI\x10\x00\x12\x10\n" +
	"\fPHASE_FUSION\x10\x012^\n" +
	"\x14FusionCaptureService\x12F\n" +
	"\rFusionCapture\x12\x17.zfusion.ZFusionRequest\x1a\x18.zfusion.ZFusionResponse\"\x000\x01B\x1eZ\x1c./internal/pkg/zfusionproto/b\x06proto3"

var (
	file_api_proto_zfusion_proto_rawDescOnce sync.Once
	file_api_proto_zfusion_proto_rawDescData []byte
)

func file_api_proto_zfusion_proto_rawDescGZIP() []byte {
	file_api_proto_zfusion_proto_rawDescOnce.Do(func() {
		file_api_proto_zfusion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_zfusion_proto_rawDesc), len(file_api_proto_zfusion_proto_rawDesc)))
	})
	return file_api_proto_zfusion_proto_rawDescData
}

var file_api_proto_zfusion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_zfusion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_zfusion_proto_goTypes = []any{
	(ZFusionResponse_PHASE)(0), // 0: zfusion.ZFusionResponse.PHASE
	(*ZFusionRequest)(nil),     // 1: zfusion.ZFusionRequest
	(*ZFusionResponse)(nil),    // 2: zfusion.ZFusionResponse
}
var file_api_proto_zfusion_proto_depIdxs = []int32{
	0, // 0: zfusion.ZFusionResponse.completion_phase:type_name -> zfusion.ZFusionResponse.PHASE
	1, // 1: zfusion.FusionCaptureService.FusionCapture:input_type -> zfusion.ZFusionRequest
	2, // 2: zfusion.FusionCaptureService.FusionCapture:output_type -> zfusion.ZFusionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_zfusion_proto_init() }
func file_api_proto_zfusion_proto_init() {
	if File_api_proto_zfusion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_zfusion_proto_rawDesc), len(file_api_proto_zfusion_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_zfusion_proto_goTypes,
		DependencyIndexes: file_api_proto_zfusion_proto_depIdxs,
		EnumInfos:         file_api_proto_zfusion_proto_enumTypes,
		MessageInfos:      file_api_proto_zfusion_proto_msgTypes,
	}.Build()
	File_api_proto_zfusion_proto = out.File
	file_api_proto_zfusion_proto_goTypes = nil
	file_api_proto_zfusion_proto_depIdxs = nil
}
