// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/zipc.proto

package zipcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrypticService_Ping_FullMethodName                   = "/zipcproto.CrypticService/Ping"
	CrypticService_FetchDecryptedTemplate_FullMethodName = "/zipcproto.CrypticService/FetchDecryptedTemplate"
	CrypticService_StoreEncryptedTemplate_FullMethodName = "/zipcproto.CrypticService/StoreEncryptedTemplate"
	CrypticService_MatchTemplate_FullMethodName          = "/zipcproto.CrypticService/MatchTemplate"
)

// CrypticServiceClient is the client API for CrypticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrypticServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	FetchDecryptedTemplate(ctx context.Context, in *FetchTemplateRequest, opts ...grpc.CallOption) (*FetchTemplateResponse, error)
	StoreEncryptedTemplate(ctx context.Context, in *StoreTemplateRequest, opts ...grpc.CallOption) (*StoreTemplateResponse, error)
	MatchTemplate(ctx context.Context, in *MatchTemplateRequest, opts ...grpc.CallOption) (*MatchTemplateResponse, error)
}

type crypticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrypticServiceClient(cc grpc.ClientConnInterface) CrypticServiceClient {
	return &crypticServiceClient{cc}
}

func (c *crypticServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, CrypticService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crypticServiceClient) FetchDecryptedTemplate(ctx context.Context, in *FetchTemplateRequest, opts ...grpc.CallOption) (*FetchTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchTemplateResponse)
	err := c.cc.Invoke(ctx, CrypticService_FetchDecryptedTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crypticServiceClient) StoreEncryptedTemplate(ctx context.Context, in *StoreTemplateRequest, opts ...grpc.CallOption) (*StoreTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreTemplateResponse)
	err := c.cc.Invoke(ctx, CrypticService_StoreEncryptedTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crypticServiceClient) MatchTemplate(ctx context.Context, in *MatchTemplateRequest, opts ...grpc.CallOption) (*MatchTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchTemplateResponse)
	err := c.cc.Invoke(ctx, CrypticService_MatchTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrypticServiceServer is the server API for CrypticService service.
// All implementations must embed UnimplementedCrypticServiceServer
// for forward compatibility.
type CrypticServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	FetchDecryptedTemplate(context.Context, *FetchTemplateRequest) (*FetchTemplateResponse, error)
	StoreEncryptedTemplate(context.Context, *StoreTemplateRequest) (*StoreTemplateResponse, error)
	MatchTemplate(context.Context, *MatchTemplateRequest) (*MatchTemplateResponse, error)
	mustEmbedUnimplementedCrypticServiceServer()
}

// UnimplementedCrypticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrypticServiceServer struct{}

func (UnimplementedCrypticServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCrypticServiceServer) FetchDecryptedTemplate(context.Context, *FetchTemplateRequest) (*FetchTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchDecryptedTemplate not implemented")
}
func (UnimplementedCrypticServiceServer) StoreEncryptedTemplate(context.Context, *StoreTemplateRequest) (*StoreTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreEncryptedTemplate not implemented")
}
func (UnimplementedCrypticServiceServer) MatchTemplate(context.Context, *MatchTemplateRequest) (*MatchTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchTemplate not implemented")
}
func (UnimplementedCrypticServiceServer) mustEmbedUnimplementedCrypticServiceServer() {}
func (UnimplementedCrypticServiceServer) testEmbeddedByValue()                        {}

// UnsafeCrypticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrypticServiceServer will
// result in compilation errors.
type UnsafeCrypticServiceServer interface {
	mustEmbedUnimplementedCrypticServiceServer()
}

func RegisterCrypticServiceServer(s grpc.ServiceRegistrar, srv CrypticServiceServer) {
	// If the following call panics, it indicates UnimplementedCrypticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrypticService_ServiceDesc, srv)
}

func _CrypticService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrypticServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrypticService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrypticServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrypticService_FetchDecryptedTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrypticServiceServer).FetchDecryptedTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrypticService_FetchDecryptedTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrypticServiceServer).FetchDecryptedTemplate(ctx, req.(*FetchTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrypticService_StoreEncryptedTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrypticServiceServer).StoreEncryptedTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrypticService_StoreEncryptedTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrypticServiceServer).StoreEncryptedTemplate(ctx, req.(*StoreTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrypticService_MatchTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrypticServiceServer).MatchTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrypticService_MatchTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrypticServiceServer).MatchTemplate(ctx, req.(*MatchTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrypticService_ServiceDesc is the grpc.ServiceDesc for CrypticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrypticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zipcproto.CrypticService",
	HandlerType: (*CrypticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CrypticService_Ping_Handler,
		},
		{
			MethodName: "FetchDecryptedTemplate",
			Handler:    _CrypticService_FetchDecryptedTemplate_Handler,
		},
		{
			MethodName: "StoreEncryptedTemplate",
			Handler:    _CrypticService_StoreEncryptedTemplate_Handler,
		},
		{
			MethodName: "MatchTemplate",
			Handler:    _CrypticService_MatchTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/zipc.proto",
}
