// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/zipc.proto

package zipcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_zipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_zipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type MatchTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchTemplateRequest) Reset() {
	*x = MatchTemplateRequest{}
	mi := &file_api_proto_zipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTemplateRequest) ProtoMessage() {}

func (x *MatchTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTemplateRequest.ProtoReflect.Descriptor instead.
func (*MatchTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{2}
}

func (x *MatchTemplateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MatchTemplateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Matched         bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	MatchScore      float32                `protobuf:"fixed32,2,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	Payload         string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,4,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchTemplateResponse) Reset() {
	*x = MatchTemplateResponse{}
	mi := &file_api_proto_zipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTemplateResponse) ProtoMessage() {}

func (x *MatchTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTemplateResponse.ProtoReflect.Descriptor instead.
func (*MatchTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{3}
}

func (x *MatchTemplateResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchTemplateResponse) GetMatchScore() float32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *MatchTemplateResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MatchTemplateResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

type FetchTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchTemplateRequest) Reset() {
	*x = FetchTemplateRequest{}
	mi := &file_api_proto_zipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTemplateRequest) ProtoMessage() {}

func (x *FetchTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTemplateRequest.ProtoReflect.Descriptor instead.
func (*FetchTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{4}
}

func (x *FetchTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FetchTemplateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           bool                   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,3,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchTemplateResponse) Reset() {
	*x = FetchTemplateResponse{}
	mi := &file_api_proto_zipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTemplateResponse) ProtoMessage() {}

func (x *FetchTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTemplateResponse.ProtoReflect.Descriptor instead.
func (*FetchTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{5}
}

func (x *FetchTemplateResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *FetchTemplateResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FetchTemplateResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

type StoreTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateType  string                 `protobuf:"bytes,2,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTemplateRequest) Reset() {
	*x = StoreTemplateRequest{}
	mi := &file_api_proto_zipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTemplateRequest) ProtoMessage() {}

func (x *StoreTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTemplateRequest.ProtoReflect.Descriptor instead.
func (*StoreTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{6}
}

func (x *StoreTemplateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreTemplateRequest) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

func (x *StoreTemplateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StoreTemplateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           bool                   `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	ResponseMessage string                 `protobuf:"bytes,2,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreTemplateResponse) Reset() {
	*x = StoreTemplateResponse{}
	mi := &file_api_proto_zipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTemplateResponse) ProtoMessage() {}

func (x *StoreTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_zipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTemplateResponse.ProtoReflect.Descriptor instead.
func (*StoreTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_zipc_proto_rawDescGZIP(), []int{7}
}

func (x *StoreTemplateResponse) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *StoreTemplateResponse) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

var File_api_proto_zipc_proto protoreflect.FileDescriptor

const file_api_proto_zipc_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/zipc.proto\x12\tzipcproto\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"0\n" +
	"\x14MatchTemplateRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x97\x01\n" +
	"\x15MatchTemplateResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x1f\n" +
	"\vmatch_score\x18\x02 \x01(\x02R\n" +
	"matchScore\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12)\n" +
	"\x10response_message\x18\x04 \x01(\tR\x0fresponseMessage\"/\n" +
	"\x14FetchTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"r\n" +
	"\x15FetchTemplateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\bR\x05state\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12)\n" +
	"\x10response_message\x18\x03 \x01(\tR\x0fresponseMessage\"n\n" +
	"\x14StoreTemplateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtemplate_type\x18\x02 \x01(\tR\ftemplateType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"X\n" +
	"\x15StoreTemplateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\bR\x05state\x12)\n" +
	"\x10response_message\x18\x02 \x01(\tR\x0fresponseMessage2\xd7\x02\n" +
	"\x0eCrypticService\x127\n" +
	"\x04Ping\x12\x16.zipcproto.PingRequest\x1a\x17.zipcproto.PingResponse\x12[\n" +
	"\x16FetchDecryptedTemplate\x12\x1f.zipcproto.FetchTemplateRequest\x1a .zipcproto.FetchTemplateResponse\x12[\n" +
	"\x16StoreEncryptedTemplate\x12\x1f.zipcproto.StoreTemplateRequest\x1a .zipcproto.StoreTemplateResponse\x12R\n" +
	"\rMatchTemplate\x12\x1f.zipcproto.MatchTemplateRequest\x1a .zipcproto.MatchTemplateResponseB?Z=github.com/Z-TAS-Solutions/Z-QryptGIN/internal/pkg/zipcproto/b\x06proto3"

var (
	file_api_proto_zipc_proto_rawDescOnce sync.Once
	file_api_proto_zipc_proto_rawDescData []byte
)

func file_api_proto_zipc_proto_rawDescGZIP() []byte {
	file_api_proto_zipc_proto_rawDescOnce.Do(func() {
		file_api_proto_zipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_zipc_proto_rawDesc), len(file_api_proto_zipc_proto_rawDesc)))
	})
	return file_api_proto_zipc_proto_rawDescData
}

var file_api_proto_zipc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_zipc_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: zipcproto.PingRequest
	(*PingResponse)(nil),          // 1: zipcproto.PingResponse
	(*MatchTemplateRequest)(nil),  // 2: zipcproto.MatchTemplateRequest
	(*MatchTemplateResponse)(nil), // 3: zipcproto.MatchTemplateResponse
	(*FetchTemplateRequest)(nil),  // 4: zipcproto.FetchTemplateRequest
	(*FetchTemplateResponse)(nil), // 5: zipcproto.FetchTemplateResponse
	(*StoreTemplateRequest)(nil),  // 6: zipcproto.StoreTemplateRequest
	(*StoreTemplateResponse)(nil), // 7: zipcproto.StoreTemplateResponse
}
var file_api_proto_zipc_proto_depIdxs = []int32{
	0, // 0: zipcproto.CrypticService.Ping:input_type -> zipcproto.PingRequest
	4, // 1: zipcproto.CrypticService.FetchDecryptedTemplate:input_type -> zipcproto.FetchTemplateRequest
	6, // 2: zipcproto.CrypticService.StoreEncryptedTemplate:input_type -> zipcproto.StoreTemplateRequest
	2, // 3: zipcproto.CrypticService.MatchTemplate:input_type -> zipcproto.MatchTemplateRequest
	1, // 4: zipcproto.CrypticService.Ping:output_type -> zipcproto.PingResponse
	5, // 5: zipcproto.CrypticService.FetchDecryptedTemplate:output_type -> zipcproto.FetchTemplateResponse
	7, // 6: zipcproto.CrypticService.StoreEncryptedTemplate:output_type -> zipcproto.StoreTemplateResponse
	3, // 7: zipcproto.CrypticService.MatchTemplate:output_type -> zipcproto.MatchTemplateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_zipc_proto_init() }
func file_api_proto_zipc_proto_init() {
	if File_api_proto_zipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_zipc_proto_rawDesc), len(file_api_proto_zipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_zipc_proto_goTypes,
		DependencyIndexes: file_api_proto_zipc_proto_depIdxs,
		MessageInfos:      file_api_proto_zipc_proto_msgTypes,
	}.Build()
	File_api_proto_zipc_proto = out.File
	file_api_proto_zipc_proto_goTypes = nil
	file_api_proto_zipc_proto_depIdxs = nil
}
