name: Deploy Z-QryptGIN API

on:
  push:
    branches:
      - main  # change if you want a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI/CD   # DO NOT TOUCH THIS!!!!! nobody goes in, nobody comes out.

    steps:
      # Step 1: Checkout repo 
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: SSH to your server and run deploy.sh
      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: /home/Z-TAS/Z-QcryptGIN/deploy.sh